spring:
  application:
    name: parking-microservice
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/parqueaya_parkingdb
    username: parkingdata
    password: 123456
    driverClassName: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: fileresources2

server:
  port: 9092
